[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
pool_escrow = "4Y3qRV52756DJgJDzvj9z5et5LX4Wr1Jm9cVEK4sS3ht"

[programs.localnet]
pool_escrow = "4Y3qRV52756DJgJDzvj9z5et5LX4Wr1Jm9cVEK4sS3ht"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test tests/"
